### ISSUE TITLE
Definer interaktionen mellem Localization og Classification

### ISSUE THREAD

**Issue by dkalaxdk** [P8-Team/Report#19]
- [x] Hvilket data sendes der imellem disse
- [x] Hvad er outputtet af samarbejdet af de to

Dokumenter de ovenstående, både ifht til rapport, men også internt

**Comment by Kaliahh** [comment]
First draft

![Flow-2 0](https://user-images.githubusercontent.com/42242841/163119953-b39233af-6025-43ce-99a5-6b7788ca9108.png)

The figure shows what happens when a WiFi-frame is received by the system. 

The first step is to check if the device has been detected before, and either creating a new entry for the new device, or passing on the found device.  The entry is found or created in a local list of devices (in memory), containing the information shown on the right in the figure. 

The next step is identification, where the device is either identified or not. In the case that it has already been identified, reidentification is made if the system is not confident enough in its identification. 

Based on the identification, the next step inserts information for a generic device if no identification was made, or inserts as much information as possible if an identification was made. This includes transmitter power, based on how much information was found (e.g. <Google, camera> -> K transmitter power, <Blink, camera> -> L transmitter power, \<camera> -> G transmitter power). A small database could be used to link information with transmitter power. 

Based on the data from the frame and the transmitter power from the previous step, the device is then localized. 

In the last step it is determined if the device should be ignored, which happens if it has passed through the system enough times while being out of range each time. There could possibly be multiple ranges (one for generic devices, and one for identified devices), and the counter (which could be different for each range) should be reset if the device is identified (and localization therefore is improved). This last step also updates the local list of devices with the information gathered this round, and the relevant information is then written to a file (for us to use later for analysis/visualisations/etc.)

Between each step, the derived information (identification, device information, position) is stored in the device in the list.
